/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myjni_JniTest */

#ifndef _Included_com_example_myjni_JniTest
#define _Included_com_example_myjni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myjni_JniTest
 * Method:    HelloJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_myjni_JniTest_HelloJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
